### ISSUE TITLE
Errors running make for peopleTracking

### ISSUE THREAD

**Issue by ashokbugude** [3dtof/DemoApplications#2]
I am using ubuntu 16.04 and running make for People Tracking and I get below errors

[ 25%] Building CXX object CMakeFiles/PeopleTracking.dir/PeopleTracking.cpp.o
[ 50%] Building CXX object CMakeFiles/PeopleTracking.dir/Horus.cpp.o
[ 75%] Building CXX object CMakeFiles/PeopleTracking.dir/TOFApp.cpp.o
/home/zayyon/Downloads/DemoApplications-master/TinTin/people_tracking/TOFApp.cpp: In function ‘void frameCallback(Voxel::DepthCamera&, const Voxel::Frame&, Voxel::DepthCamera::FrameType)’:
/home/zayyon/Downloads/DemoApplications-master/TinTin/people_tracking/TOFApp.cpp:40:89: error: invalid conversion from ‘const Voxel::Frame_’ to ‘Voxel::Frame_’ [-fpermissive]
 e _nf = dynamic_cast<const Voxel::Frame *>(new Voxel::DepthFrame(_f));  
                                                                     ^
/home/zayyon/Downloads/DemoApplications-master/TinTin/people_tracking/TOFApp.cpp:45:98: error: invalid conversion from ‘const Voxel::Frame_’ to ‘Voxel::Frame_’ [-fpermissive]
 ynamic_cast<const Voxel::Frame *>(new Voxel::XYZIPointCloudFrame(_f));  
                                                                     ^
CMakeFiles/PeopleTracking.dir/build.make:110: recipe for target 'CMakeFiles/PeopleTracking.dir/TOFApp.cpp.o' failed
make[2]: *_\* [CMakeFiles/PeopleTracking.dir/TOFApp.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/PeopleTracking.dir/all' failed
make[1]: **\* [CMakeFiles/PeopleTracking.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by larrylisky** [comment]
Did you first build and install voxelsdk?

-Larry

**Comment by ashokbugude** [comment]
Yes I have built and installed voxelsdk ;

libvoxelpcl.so is not installed ( needed for other apps like handTracking etc).Can I please know how do I get it installed

Below is the error I am getting when I run make command for people Tracking
/home/zayyon/Downloads/DemoApplications-master/TinTin/people_tracking/TOFApp.cpp:45:98: error: invalid conversion from ‘const Voxel::Frame’ to ‘Voxel::Frame’ [-fpermissive]
ynamic_cast(new Voxel::XYZIPointCloudFrame(f));

**Comment by larrylisky** [comment]
Make sure voxelsdk is installed in /usr/include not /usr/local.  If voxelsdk is correctly installed, building the demo project by  

(1) make a ‘build’ directory and ‘cd’ to it.

(2) cmake ..

(3)  make

-Larry

**Comment by ashokbugude** [comment]
Hi,

I have modified the title form "CameraSystem.h: No such file or directory" to "Errors running make for peopleTracking"

The code is able to find voxelsdk and CameraSystem.h  
The issue is related to code as described below

/home/zayyon/Downloads/DemoApplications-master/TinTin/people_tracking/TOFApp.cpp:45:98: error: invalid conversion from ‘const Voxel::Frame’ to ‘Voxel::Frame’ [-fpermissive]
ynamic_cast(new Voxel::XYZIPointCloudFrame(f));

**Comment by larrylisky** [comment]
Which version of voxelsdk?  The code compiled against voxelsdk 0.6.3

-Larry

**Comment by larrylisky** [comment]
Also it seems to be a ‘const’ issue.  If you need to remove const or typecast to const.
Or fix by making -fpermissive?

-Larry

**Comment by ashokbugude** [comment]
I think i have voxel 0.6.3 , not sure how to check as i  have renamed voxel 0.6.3 to voxel in usr/include folder.

I shall make the code changes as suggested by you and try running again

While installing voxel , I have disabled swig 3.0  in ccmake as I face errors while installing with it as described in https://github.com/3dtof/voxelsdk/issues/89

Even with 0.6.4 I face the same issues as shown below
[ 32%] Built target voxel
[ 32%] Swig source
/home/zayyon/Downloads/voxelsdk-master/Voxel/SWIG/standard_container.i:120: Error: Macro '%std_nodefconst_type' redefined,
/usr/share/swig3.0/std/std_container.i:135: Error: previous definition of '%std_nodefconst_type'.
Voxel/SWIG/CMakeFiles/_Voxel.dir/build.make:61: recipe for target 'lib/python2.7/VoxelPYTHON_wrap.cxx' failed
make[2]: **\* [lib/python2.7/VoxelPYTHON_wrap.cxx] Error 1
CMakeFiles/Makefile2:174: recipe for target 'Voxel/SWIG/CMakeFiles/_Voxel.dir/all' failed
make[1]: **\* [Voxel/SWIG/CMakeFiles/_Voxel.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: **\* [all] Error 2

Could the issue of the invalid conversion from ‘const Voxel::Frame’ to ‘Voxel::Frame’ [-fpermissive]' be due to voxel not installed with swig 3.0 ?I think no

Could you please send me libvoxelpcl.so file as its not installed in my system. I need it to run other apps like handTracking as I get below errors

zayyon@zayyon-Lenovo-ideapad-300-15ISK:~/Downloads/DemoApplications-master/TinTin/hand_tracking/build$ sudo make
[sudo] password for zayyon: 
Scanning dependencies of target main
[ 25%] Building CXX object CMakeFiles/main.dir/main.cpp.o
[ 50%] Building CXX object CMakeFiles/main.dir/Jive.cpp.o
[ 75%] Building CXX object CMakeFiles/main.dir/TOFApp.cpp.o
make[2]: **\* No rule to make target '/usr/lib/libvoxelpcl.so', needed by 'main'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/main.dir/all' failed
make[1]: **\* [CMakeFiles/main.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: **\* [all] Error 2

Thanks

**Comment by ashokbugude** [comment]
I am able to remove const keywords as described in error messages and was able to run make
