### ISSUE TITLE
People Tracking Morph Image not clear

### ISSUE THREAD

**Issue by ashokbugude** [3dtof/DemoApplications#3]
Hi I am using ubuntu 16.04 and OPT8241 and have run people tracking which shows below output
![peopletracking](https://cloud.githubusercontent.com/assets/10016848/19212122/96f1a74c-8d68-11e6-90c3-4a8c52ad0fe6.png)

I expected it to be as shown in video in https://larrylisky.com/2016/03/03/people-tracking-using-a-depth-camera/   ie, my body should be white in morph image .

Could I please know what code/settings need to be made to obtain results as shown in the video

**Comment by ashokbugude** [comment]
Another image with a person standing behind 
![peopletrackingotp8241](https://cloud.githubusercontent.com/assets/10016848/19212358/14d0b91a-8d6d-11e6-9a65-784b48b50667.png)

**Comment by larrylisky** [comment]
@ashokbugude: to make it look like the image in my blog the 'drawing' Mat should be initialized with amplitude map.  Also in your top image there is saturation near your 'hand'.  You need to turn down the integration duty cycle.

**Comment by larrylisky** [comment]
Also you need to first initialize the reference 'background', without anyone in the field of view, by hitting the 'b' key.

**Comment by ashokbugude** [comment]
Thanks, I shall try
