### ISSUE TITLE
People Tracking Image not Show

### ISSUE THREAD

**Issue by city0601** [3dtof/DemoApplications#5]
Hi  I am using ubuntu 14.04 ,VoxelSDK 0.6.3 and OPT8241 and have run people tracking which shows below output

Who Can help me

![screenshot from 2016-10-25 17 24 10](https://cloud.githubusercontent.com/assets/23050662/19680531/a54add22-9ad8-11e6-9916-0d439ecb0568.png)

**Comment by larrylisky** [comment]
Are you running a virtual machine?  If so please try without VM. 

-Larry

**Comment by city0601** [comment]
Hi Larry 
OK,I will try it .
Thanks.

**Comment by city0601** [comment]
Hi Larray
Thanks,The issue is close
thank you so much
