### ISSUE TITLE
How can show distance at the frame

### ISSUE THREAD

**Issue by city0601** [3dtof/DemoApplications#6]
Hi 
I run people tracking , how can show distance at the frame when detect object?
Can i use whice one API?
Thanks.

**Comment by larrylisky** [comment]
OpenCV has a putText() function. 

http://docs.opencv.org/2.4/modules/core/doc/drawing_functions.html#puttext

-Larry

**Comment by city0601** [comment]
Hi Larry
Do you know how about VoxelSDK API can get object distance ?
Can i use which one VoxelSDK API?
Thanks.

**Comment by larrylisky** [comment]
Distance is contained in a frame class, not returned from a call to 
API.   Look in top of this file, Horus::update(Frame *frame) function.  
XYZIPointCloudFrame *frm points to an 320x240 array of (x,y,z) points in 
unit of meter.

https://github.com/3dtof/DemoApplications/blob/master/TinTin/people_tracking/Horus.cpp

-Larry

**Comment by city0601** [comment]
Hi Larry
Ok, Thank you so much.
